const data = [
  {
    id: 1,
    brand: "adidas",
    name: "Cartoon Astronaut T-Shirts 1",
    price: 33,
    img: "img/products/f1.jpg",
  },
  {
    id: 2,
    brand: "nike",
    name: "Cartoon Astronaut T-Shirts 2",
    price: 73,
    img: "img/products/f2.jpg",
  },
  {
    id: 3,
    brand: "NB",
    name: "Cartoon Astronaut T-Shirts 3",
    price: 81,
    img: "img/products/f3.jpg",
  },
  {
    id: 4,
    brand: "puma",
    name: "Cartoon Astronaut T-Shirts 4",
    price: 27,
    img: "img/products/f4.jpg",
  },
  {
    id: 5,
    brand: "adidas",
    name: "Cartoon Astronaut T-Shirts 5",
    price: 92,
    img: "img/products/f5.jpg",
  },
  {
    id: 6,
    brand: "puma",
    name: "Cartoon Astronaut T-Shirts 6",
    price: 29,
    img: "img/products/f6.jpg",
  },
  {
    id: 7,
    brand: "nb",
    name: "Cartoon Astronaut T-Shirts 7",
    price: 36,
    img: "img/products/f7.jpg",
  },
  {
    id: 8,
    brand: "adidas",
    name: "Cartoon Astronaut T-Shirts 8",
    price: 65,
    img: "img/products/f8.jpg",
  },
  {
    id: 9,
    brand: "adidas",
    name: "Cartoon Astronaut T-Shirts 9",
    price: 11,
    img: "/img/products/n1.jpg",
  },
  {
    id: 10,
    brand: "nike",
    name: "Cartoon Astronaut T-Shirts 10",
    price: 29,
    img: "img/products/n2.jpg",
  },
  {
    id: 11,
    brand: "NB",
    name: "Cartoon Astronaut T-Shirts 11",
    price: 87,
    img: "img/products/n3.jpg",
  },
  {
    id: 12,
    brand: "puma",
    name: "Cartoon Astronaut T-Shirts 12",
    price: 43,
    img: "img/products/n4.jpg",
  },
  {
    id: 13,
    brand: "adidas",
    name: "Cartoon Astronaut T-Shirts 13",
    price: 55,
    img: "img/products/n5.jpg",
  },
  {
    id: 14,
    brand: "puma",
    name: "Cartoon Astronaut T-Shirts 14",
    price: 37,
    img: "img/products/n6.jpg",
  },
  {
    id: 15,
    brand: "nb",
    name: "Cartoon Astronaut T-Shirts 15",
    price: 61,
    img: "img/products/n7.jpg",
  },
  {
    id: 16,
    brand: "adidas",
    name: "Cartoon Astronaut T-Shirts 16",
    price: 91,
    img: "img/products/n8.jpg",
  },
];
